Wem 855
wepala/product-module pull request #22
Opened 2021-07-21 12:28 UTC by atoniaw

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2021-07-21 17:32 UTC, atoniaw commented
Updated https://github.com/wepala/product-module/blob/6c13fb8b78fb8f8c7fb3d0aef626e1ba5d50408c/features/wem-496-import-products.feature#L56 since type provided and type tested against did not match.

2021-07-22 09:22 UTC, akeemphilbert requested changes

2021-07-22 09:22 UTC, akeemphilbert commented on dtos.go
>  	AccountID        string        `json:"account_id"`
Remove this as well. I know you mentioned that some were used in query calls though I'm not sure what you mean by that exactly. Ideally since I'll have to go through and make updates I'd like to only have to do it once

2021-07-22 14:40 UTC, akeemphilbert approved these changes

2021-07-22 14:41 UTC, merged